# Generated by Django 2.0.2 on 2018-06-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favbooks',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='favmovies',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
