# Generated by Django 2.0.2 on 2018-06-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
